name: Node.js Build-Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14.7

    - name: Configure GitHub Packages authentication
      run: npm config set //npm.pkg.github.com/:_authToken ${{ secrets.CODESTOTHESTARS_GITHUB_TOKEN }}

    - env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      name: Install dependencies
      run: npm install

    - name: Build code
      run: npm run build

    - name: Unit test
      run: npm test

    - name: Lint code
      run: npm run lint
