jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      name: Create release
      uses: actions/create-release@v1
      with:
        draft: false
        prerelease: false
        release_name: ${{ github.ref }}
        tag_name: ${{ github.ref }}

name: Create GitHub Release

on:
  push:
    tags:
      - "v*"
